### ISSUE TITLE
TypeError: expected str, bytes or os.PathLike object, not NoneType

### ISSUE THREAD

**Issue by FanScy** [TonghanWang/DOP#5]
Hi, thanks for sharing your excellent work!!
I followed your installation tutorial, but I encounter the problem of sacred == 0.7.2(from oxwhirl/fork)
`Traceback (most recent call last):
  File "src/main.py", line 19, in <module>
    ex = Experiment("pymarl")
  File "/home/public/anaconda3/envs/torch/lib/python3.8/site-packages/sacred/experiment.py", line 72, in __init__
    super(Experiment, self).__init__(path=name,
  File "/home/public/anaconda3/envs/torch/lib/python3.8/site-packages/sacred/ingredient.py", line 57, in __init__
    gather_sources_and_dependencies(_caller_globals)
  File "/home/public/anaconda3/envs/torch/lib/python3.8/site-packages/sacred/dependencies.py", line 487, in gather_sources_and_dependencies
    sources = gather_sources(globs, experiment_path)
  File "/home/public/anaconda3/envs/torch/lib/python3.8/site-packages/sacred/dependencies.py", line 440, in get_sources_from_imported_modules
    return get_sources_from_modules(iterate_imported_modules(globs), base_path)
  File "/home/public/anaconda3/envs/torch/lib/python3.8/site-packages/sacred/dependencies.py", line 409, in get_sources_from_modules
    filename = os.path.abspath(mod.__file__)
  File "/home/public/anaconda3/envs/torch/lib/python3.8/posixpath.py", line 374, in abspath
    path = os.fspath(path)
TypeError: expected str, bytes or os.PathLike object, not NoneType`

How can I do?

**Comment by TonghanWang** [comment]
Hi FanScy,

I guess a newer version of sacred can solve this problem. You can first install it by running

`pip install git+https://github.com/oxwhirl/smac.git`

If this does not work, add an if clause

`if mod.__file__ is not None`

before this line!
